# Twitter parameters
consumer_key: xcQnowmpUKU7KTWjiyg
consumer_secret: fuenh1AbUpKSrFTMUvRO4w9tKPE9w5cUgRnf7QNgE
callback_urls: 
  production: http://twitter-zombie.heroku.com/twitter/callback
  development: http://dev.twipler.com:3000/twitter/callback