# Twitter parameters
consumer_key: kasdhfkjas
consumer_secret: kashdfkdsf
callback_urls: 
  production: http://twitter-zombie.heroku.com/twitter/callback
  development: http://dev.twipler.com:3000/twitter/callback
